export const galleriesCarouselData = [
  {
    id: 0,
    serialNo: '01',
    title: 'Basic Level Class',
    type: 'image',
    src: '/home/gallery-1.png',
  },
  {
    id: 1,
    serialNo: '02',
    title: 'Basic Level Class',
    type: 'image',
    src: '/home/gallery-2.png',
  },
  {
    id: 2,
    serialNo: '03',
    title: 'Primary Level Class',
    type: 'image',
    src: '/home/gallery-3.png',
  },
  {
    id: 3,
    serialNo: '04',
    title: 'Intermediate Level Class',
    type: 'image',
    src: '/home/gallery-4.png',
  },
  {
    id: 4,
    serialNo: '05',
    title: 'Advanced Level Class',
    type: 'image',
    src: '/home/gallery-5.png',
  },
  {
    id: 5,
    serialNo: '06',
    title: 'Expert Level Class',
    type: 'image',
    src: '/home/gallery-6.png',
  },
  {
    id: 7,
    serialNo: '07',
    title: 'Expert Level Class',
    type: 'video',
    src: '/home/video/school-promo.mov',
  },
]
